# Generated by Django 5.1.3 on 2024-11-25 16:07

import almacen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=almacen.models.upload_to_producto),
        ),
    ]
