# Generated by Django 5.1.3 on 2024-11-25 16:41

import almacen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=almacen.models.upload_to_category),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=almacen.models.upload_to_user),
        ),
    ]
