# Generated by Django 5.1.3 on 2024-12-02 08:28

import appstore.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=appstore.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
    ]
