# Generated by Django 5.1.3 on 2024-12-02 09:19

import appstore.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=appstore.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
